-- Create table for Daily Highlights (Weekly Focus)
create table if not exists daily_highlights (
  id bigint generated by default as identity primary key,
  user_id uuid references auth.users not null,
  key text not null, -- Format: "YYYY-MM-DD_Index"
  text text,
  completed boolean default false,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  updated_at timestamp with time zone default timezone('utc'::text, now()) not null,
  unique(user_id, key)
);

-- Enable RLS
alter table daily_highlights enable row level security;

-- Policies
create policy "Users can view their own highlights"
  on daily_highlights for select
  using ( auth.uid() = user_id );

create policy "Users can insert their own highlights"
  on daily_highlights for insert
  with check ( auth.uid() = user_id );

create policy "Users can update their own highlights"
  on daily_highlights for update
  using ( auth.uid() = user_id );

create policy "Users can delete their own highlights"
  on daily_highlights for delete
  using ( auth.uid() = user_id );
